require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/assessments", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Assessment. As you add validations to Assessment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Assessment.create! valid_attributes
      get assessments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      assessment = Assessment.create! valid_attributes
      get assessment_url(assessment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      assessment = Assessment.create! valid_attributes
      get new_assessment_url(assessment)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      assessment = Assessment.create! valid_attributes
      get edit_assessment_url(assessment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Assessment" do
        expect {
          post assessments_url, params: {assessment: valid_attributes}
        }.to change(Assessment, :count).by(1)
      end

      it "redirects to the created assessment" do
        post assessments_url, params: {assessment: valid_attributes}
        expect(response).to redirect_to(assessment_url(Assessment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Assessment" do
        expect {
          post assessments_url, params: {assessment: invalid_attributes}
        }.to change(Assessment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post assessments_url, params: {assessment: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested assessment" do
        assessment = Assessment.create! valid_attributes
        patch assessment_url(assessment), params: {assessment: new_attributes}
        assessment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the assessment" do
        assessment = Assessment.create! valid_attributes
        patch assessment_url(assessment), params: {assessment: new_attributes}
        assessment.reload
        expect(response).to redirect_to(assessment_url(assessment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        assessment = Assessment.create! valid_attributes
        patch assessment_url(assessment), params: {assessment: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested assessment" do
      assessment = Assessment.create! valid_attributes
      expect {
        delete assessment_url(assessment)
      }.to change(Assessment, :count).by(-1)
    end

    it "redirects to the assessments list" do
      assessment = Assessment.create! valid_attributes
      delete assessment_url(assessment)
      expect(response).to redirect_to(assessments_url)
    end
  end
end
